workflows:
  react-native-apk:
    name: React Native Build (No CMake Crash)
    environment:
      node: 20.9.0
      java: 17
    scripts:
      - name: Clean install and setup
        script: |
          rm -rf node_modules android/.gradle
          npm install
          cd android && ./gradlew clean && cd ..
      - name: Bypass reanimated native CMake build
        script: |
          echo "⚙️ Skipping Reanimated native build..."
          mkdir -p node_modules/react-native-reanimated/android/src/main/jni
          echo "// dummy cmake to skip build" > node_modules/react-native-reanimated/android/src/main/jni/CMakeLists.txt
      - name: Bundle JS
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
