workflows:
  react-native-workflow:
    name: React Native Android APK Build
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.ssg"
      node: 20.9.0  # 👈 FIXED: Use Node 20+
      java: 17      # ✅ Required by AGP 8+
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Clean and prepare assets
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/
      - name: Build release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
