workflows:
  react-native-workflow:
    name: React Native Android APK Build
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.ssg"  # update if your package name is different
      node: 20.9.0               # ✅ Fix Metro "os.availableParallelism" error
      java: 17                   # ✅ Required for Gradle 8 + Android Gradle Plugin
    scripts:
      - name: Clean install and clean gradle
        script: |
          rm -rf node_modules android/.gradle
          npm install
          cd android
          ./gradlew clean
          cd ..
      - name: Workaround for reanimated CMake issue
        script: |
          cd node_modules/react-native-reanimated
          mkdir -p android/src/main/jni
          echo "// skip cmake in CI" > android/src/main/jni/CMakeLists.txt
          cd ../../../
      - name: Bundle React Native assets
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
