workflows:
  react-native-workflow:
    name: React Native Android APK Build
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.ssg"  # replace with your actual package if different
      node: 16.20.0
      java: 11
      android: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
