workflows:
  react-native-workflow:
    name: React Native Android APK Build
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.ssg"  # Replace with your actual package name
      node: 16.20.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
