workflows:
  react-native-workflow:
    name: React Native Android Build (No CMake Crash)
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.ssg"
      node: 20.9.0     # ✅ Required for Metro bundler (os.availableParallelism fix)
      java: 17         # ✅ Required for AGP 8.x and Gradle 8.14
    scripts:
      - name: Clean and reinstall
        script: |
          rm -rf node_modules android/.gradle
          npm install
          cd android && ./gradlew clean && cd ..
      - name: Skip Reanimated CMake
        script: |
          echo "Bypassing Reanimated native CMake build..."
          cd node_modules/react-native-reanimated
          mkdir -p android/src/main/jni
          echo "// bypass cmake in CI/CD build" > android/src/main/jni/CMakeLists.txt
          cd ../../../
      - name: Bundle React Native JavaScript
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/
      - name: Build the APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
