name: Build APK in Cloud

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 🟩 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: 📥 Install dependencies
        run: npm install

      - name: 🧪 Show Java version
        run: |
          echo "JAVA_HOME = $JAVA_HOME"
          java -version

      - name: 🧱 Build APK
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }} # This forces Gradle to use Java 17

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
