name: Build APK in Cloud

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: npm install

      - name: Debug Java
        run: |
          echo "JAVA_HOME = $JAVA_HOME"
          java -version

      - name: Build APK
        run: |
          echo "org.gradle.java.home=${{ steps.setup-java.outputs.path }}" >> android/gradle.properties
          export JAVA_HOME=${{ steps.setup-java.outputs.path }}
          cd android
          ./gradlew assembleRelease --no-daemon
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
